# GitHub Sponsors funding for this project.
#
# Works regardless of which licence is chosen. Note that sponsorship cannot be made
# a *condition* of a licence in any clean, enforceable way - a licence forbids things,
# it does not invoice. What a licence can do is withhold a right that a commercial
# reseller needs, which is what creates the reason to talk.
#
# Replace with the account or org that should receive sponsorship.
github: [IT-Cru]
